language: node_js
sudo: false
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm test
before_deploy:
  - npm run build:polymer
  - echo "$HEROKU_API" | docker login -u "$HEROKU_USER" --password-stdin registry.heroku.com
deploy:
  provider: script
  skip_cleanup: true
  script: bash travis-heroku-deploy.sh
  on:
    branch: master
